version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  db:
      image: postgres
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: mydb

  pgadmin:
    image: thajeztah/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: myuser
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "5050:5050"
    depends_on:
      - db       
  
volumes:
  static:

